### ISSUE TITLE
Gestion des réglages sur mobile

### ISSUE THREAD

**Issue by tomasit** [noted-eip/mobile#2]
### Description
En tant qu’utilisateur je veux parametrer mon application

### Definition of Done
- [ ]  Création d’un écran de réglage
    - [ ]  Gestion des groupes
    - [ ]  Gestion des notes
- [ ]  Liaison avec le backend
    - [ ]  changer l’administrateur
    - [ ]  Rajouter/supprimer des personnes du groupe
- [ ]  Faire des test sur la récupération des notes contenu dans un dossier

### Estimation
Estimée à 2.5 JH

**Comment by balthi-tech** [comment]
DOD report in other user story
